version: '3'

services:
  ocsapplication:
    image: ocsinventory/ocsinventory-docker-image:2.6
    container_name : ocsinventory-server
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "perlcomdata:/etc/ocsinventory-server"
      - "extensionsdata:/usr/share/ocsinventory-reports/ocsreports/extensions"
      - "varlibdata:/var/lib/ocsinventory-reports"
      - "httpdconfdata:/etc/httpd/conf.d"
    environment:
      OCS_DB_SERVER: ocsdb
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
    links:
      - ocsdb
  ocsdb :
    image : mysql:5.7
    container_name : ocsinventory-db
    restart: always
    ports :
      - 3306:3306
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - sqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : rootpass
      MYSQL_USER : ocsuser
      MYSQL_PASSWORD : ocspass
      MYSQL_DATABASE : ocsweb
    
volumes:
  perlcomdata:
  extensionsdata:
  varlibdata:
  httpdconfdata:
  sqldata:
  